version: '3'

services:
  core:
    stdin_open: true
    tty: true
    container_name: core_container
    build: .
    command: bash -c "python manage.py migrate --noinput && gunicorn ShortLinks.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./:/src
    expose:
      - 8000
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: 'db'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    volumes:
      - ./database:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    links:
      - core
    depends_on:
      - core

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'

volumes:
  db_data:

