version: '3'

services:
  db:
    image: mysql:5.7
    container_name: 'db'
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'my_admin'
       MYSQL_PASSWORD: 'testing321'
       MYSQL_ROOT_PASSWORD: 'testing321'

    volumes:
          - ./database:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'

volumes:
  db_data:

