# Generated by Django 3.1.7 on 2021-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''SET GLOBAL event_scheduler = ON;''',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql='''CREATE EVENT remove_scheduler
                    ON SCHEDULE EVERY 1 HOUR
                    DO DELETE FROM
                    Core_link WHERE created_at < NOW() - INTERVAL 7 DAY;''',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
