# Generated by Django 3.1.7 on 2021-03-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('Core', '0002_auto_20210325_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
